GOOS_Sample/Models/BudgetViewModels.cs
using System.ComponentModel.DataAnnotations;
using System.Runtime.InteropServices;

namespace GOOS_Sample.Models
{
    public class BudgetViewModel
    {
        [Required]
        public string Month { get; set; }

        [Required]
        public string Amount { get; set; }
    }    
}

GOOS_Sample/Controllers/BudgetController.cs
using System;
using System.Web.Mvc;
using GOOS_Sample.Models;
using GOOS_Sample.Services;

namespace GOOS_Sample.Controllers
{
    public class BudgetController : Controller
    {
        private readonly IBudgetService _service;

        public BudgetController(IBudgetService service)
        {
            this._service = service;
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddBudget(BudgetViewModel model)
        {
            this._service.Add(model);

            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            var model = this._service.Get();

            return View(model);
        }
    }
}

GOOS_Sample/Views/Budget/Add.cshtml
@model GOOS_Sample.Models.BudgetViewModel
@{
    ViewBag.Title = "Add Budget";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("AddBudget", "Budget", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <h4>Add Budget</h4>
    <hr />
    <div class="form-group">
        <div class="col-md-10">
            @Html.TextBoxFor(i => i.Month, htmlAttributes: new { id = "month" })
            @Html.TextBoxFor(i => i.Amount, htmlAttributes: new { id = "amount" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="save" id="save" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GOOS_Sample/Views/Budget/List.cshtml
@model GOOS_Sample.Models.BudgetViewModel
@{
    ViewBag.Title = "Budget List";
}

<h2>@ViewBag.Title.</h2>
<hr />
<div class="form-group">
    <div class="col-md-10">
        Month : @Html.TextBoxFor(i => i.Month, htmlAttributes: new { id = "month" })
        Amount : @Html.TextBoxFor(i => i.Amount, htmlAttributes: new { id = "amount" })
    </div>
</div>